apiVersion: v1
kind: ConfigMap
metadata:
  name: service-conf
data:
       authhostinternal: auth-clusterip-service:9191
       backendhost: backend-clusterip-service:8080
       authhostextranal: 34.72.11.24:30037
